#define ACTION_NUM 53
#define ACTION_LEN 80
char action[ACTION_NUM][ACTION_LEN] = {
	"disrespects my theme",
	"changes my cursor",
	"takes ages to start",
	"causes screen tearing",
	"makes my fans spin up",
	"makes my blood boil",
	"boils my piss",
	"will be abandoned",
	"is the \"extend\" step",
	"will be sold to Microsoft™",
	"is spyware",
	"is malware",
	"hates freedom",
	"hates my donkey",
	"hates my mom",
	"is not UNIX™",
	"hates Linux",
	"is toxic to penguins",
	"thinks the Earth is flat",
	"bursts my bubble",
	"busts my balls",
	"sleeps with the fishes",
	"sleeps with the donkeys",
	"sucks",
	"blows",
	"blows my donkey",
	"interferes with my donkey",
	"interferes with my donkey\'s balls",
	"interferes with my audio server",
	"can\'t see my external drive",
	"shits in my external drive",
	"corrupts my external drive",
	"interferes with my external drive",
	"spreads coronavirus",
	"spreads 5G networks",
	"causes cancer",
	"has leprosy",
	"spreads the bad AIDS",
	"is shit",
	"is worse than shit",
	"interferes with my mom",
	"corrupts my mom",
	"shits in my mom\'s external drive",
	"corrupts my donkey",
	"is technologically inferior to flatpak",
	"is ethically inferior to flatpak",
	"is ethically inferior to my mom",
	"is ethically inferior to my donkey",
	"should stay hidden in a dot directory",
	"is literally Microsoft",
	"will be gone in 2 years",
	"causes fragmentation",
	"causes global warming"
};
